services:
  postgres:
    image: postgres:15
    container_name: postgresql-v15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - shortlink-network

  traefik:
    image: traefik:v3.5.0
    container_name: traefik-v3.5.0
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ../traefik/config:/etc/traefik/config:ro
    networks:
      - shortlink-network

  url-service:
    build:
      context: ../../apps/services/url-service
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../../apps/services/url-service:/app
    env_file:
      - ../../apps/services/url-service/.env
    depends_on:
      - postgres
    networks:
      - shortlink-network

volumes:
  postgres_data:

networks:
  shortlink-network:
    driver: bridge
