FROM python:3.11-slim

# stable gcc version
RUN apt-get update && apt-get install -y --no-install-recommends\
    gcc=12.5 \
    && rm -rf /var/lib/apt/lists/*

# stable poetry version
RUN pip install poetry==2.1.4 --no-cache-dir

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-root

COPY . .

ENV PYTHONPATH=/app/src

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "src"]
