http:
  routers:
    url-service:
      rule: "Host(`shortlink`)"
      service: url-service
      entryPoints:
        - web

  services:
    url-service:
      loadBalancer:
        servers:
          - url: "http://url-service:8000"
